name: CI
on: [push, pull_request]

env:
  SEQ_DB: sequelize_test
  SEQ_USER: sequelize_test
  SEQ_PW: sequelize_test

jobs:
  test-mysql-mariadb:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: MySQL 5.7
            image: mysql:5.7
            dialect: mysql
            node-version: 10
          - name: MySQL 5.7
            image: mysql:5.7
            dialect: mysql
            node-version: 12
          - name: MariaDB 10.3
            image: mariadb:10.3
            dialect: mariadb
            node-version: 10
          - name: MariaDB 10.3
            image: mariadb:10.3
            dialect: mariadb
            node-version: 12
    name: ${{ matrix.name }} (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    services:
      mysql:
        image: ${{ matrix.image }}
        env:
          MYSQL_DATABASE: sequelize_test
          MYSQL_USER: sequelize_test
          MYSQL_PASSWORD: sequelize_test
          MYSQL_ROOT_PASSWORD: sequelize_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin -usequelize_test -psequelize_test status" --health-interval 10s --health-timeout 5s --health-retries 5 --tmpfs /var/lib/mysql:rw
    env:
      DIALECT: ${{ matrix.dialect }}
    steps:
      - run: mysql --host 127.0.0.1 --port 3306 -uroot -psequelize_test -e "GRANT ALL ON *.* TO 'sequelize_test'@'%' with grant option; FLUSH PRIVILEGES;"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Unit Tests
        run: npm run test-unit
      - name: Integration Tests
        run: npm run test-integration
